//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Order
    {
        public System.Guid Id { get; set; }
        [DisplayName("Описание")]
        public string Description { get; set; }
        [DisplayName("Инвентарь")]
        public int InventId { get; set; }
        [DisplayName("Количество")]
        public int Count { get; set; }
        [DisplayName("Цена")]
        public int Cost { get; set; }
        [DisplayName("Время создания")]
        public System.DateTime Date { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
